export const capitalsQuizData = [
    {
      id: 1,
      difficulty: "easy",
      question: "France",
      options: ["Paris", "Berlin", "Madrid", "Rome"],
    },
    {
      id: 2,
      difficulty: "easy",
      question: "Italy",
      options: ["Rome", "Paris", "Lisbon", "Athens"],
    },
    {
      id: 3,
      difficulty: "easy",
      question: "Spain",
      options: ["Madrid", "Barcelona", "Seville", "Valencia"],
    },
    {
      id: 4,
      difficulty: "easy",
      question: "Germany",
      options: ["Berlin", "Munich", "Frankfurt", "Hamburg"],
    },
    {
      id: 5,
      difficulty: "easy",
      question: "the United Kingdom",
      options: ["London", "Manchester", "Liverpool", "Edinburgh"],
    },
    {
      id: 6,
      difficulty: "easy",
      question: "Belarus",
      options: ["Minsk", "Brest", "Mogilev", "Vitebsk"],
    },
    {
      id: 7,
      difficulty: "easy",
      question: "China",
      options: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"],
    },
    {
      id: 8,
      difficulty: "easy",
      question: "India",
      options: ["New Delhi", "Mumbai", "Bangalore", "Kolkata"],
    },
    {
      id: 9,
      difficulty: "easy",
      question: "Brazil",
      options: ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    },
    {
      id: 10,
      difficulty: "easy",
      question: "the United States",
      options: ["Washington, D.C.", "New York", "Los Angeles", "Chicago"],
    },
    {
      id: 11,
      difficulty: "easy",
      question: "Egypt",
      options: ["Cairo", "Alexandria", "Giza", "Luxor"],
    },
    {
      id: 12,
      difficulty: "easy",
      question: "Argentina",
      options: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
    },
    {
      id: 13,
      difficulty: "easy",
      question: "Mexico",
      options: ["Mexico City", "Guadalajara", "Monterrey", "Cancún"],
    },
    {
      id: 14,
      difficulty: "easy",
      question: "Turkey",
      options: ["Ankara", "Istanbul", "Izmir", "Antalya"],
    },
    {
      id: 15,
      difficulty: "easy",
      question: "Canada",
      options: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
    },
    {
      id: 16,
      difficulty: "medium",
      question: "Australia",
      options: ["Canberra", "Sydney", "Melbourne", "Perth"],
    },
    {
      id: 17,
      difficulty: "medium",
      question: "Japan",
      options: ["Tokyo", "Kyoto", "Osaka", "Nagoya"],
    },
    {
      id: 18,
      difficulty: "medium",
      question: "South Korea",
      options: ["Seoul", "Busan", "Incheon", "Daegu"],
    },
    {
      id: 19,
      difficulty: "medium",
      question: "South Africa",
      options: ["Pretoria", "Cape Town", "Johannesburg", "Durban"],
    },
    {
      id: 20,
      difficulty: "medium",
      question: "Saudi Arabia",
      options: ["Riyadh", "Jeddah", "Mecca", "Medina"],
    },
    {
      id: 21,
      difficulty: "medium",
      question: "Thailand",
      options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"],
    },
    {
      id: 22,
      difficulty: "medium",
      question: "Sweden",
      options: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"],
    },
    {
      id: 23,
      difficulty: "medium",
      question: "Norway",
      options: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
    },
    {
      id: 24,
      difficulty: "medium",
      question: "Finland",
      options: ["Helsinki", "Tampere", "Turku", "Oulu"],
    },
    {
      id: 25,
      difficulty: "medium",
      question: "New Zealand",
      options: ["Wellington", "Auckland", "Christchurch", "Dunedin"],
    },
    {
      id: 26,
      difficulty: "medium",
      question: "Portugal",
      options: ["Lisbon", "Porto", "Braga", "Coimbra"],
    },
    {
      id: 27,
      difficulty: "medium",
      question: "Greece",
      options: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
    },
    {
      id: 28,
      difficulty: "medium",
      question: "the Netherlands",
      options: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
    },
    {
      id: 29,
      difficulty: "medium",
      question: "Belgium",
      options: ["Brussels", "Antwerp", "Ghent", "Bruges"],
    },
    {
      id: 30,
      difficulty: "medium",
      question: "Poland",
      options: ["Warsaw", "Krakow", "Wroclaw", "Gdansk"],
    },

    {
      id: 31,
      difficulty: "hard",
      question: "Kazakhstan",
      options: ["Nur-Sultan", "Almaty", "Shymkent", "Aktobe"],
    },
    {
      id: 32,
      difficulty: "hard",
      question: "Mongolia",
      options: ["Ulaanbaatar", "Darkhan", "Erdenet", "Choibalsan"],
    },
    {
      id: 33,
      difficulty: "hard",
      question: "Bolivia",
      options: ["Sucre", "La Paz", "Cochabamba", "Santa Cruz"],
    },
    {
      id: 34,
      difficulty: "hard",
      question: "Sri Lanka",
      options: ["Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"],
    },
    {
      id: 35,
      difficulty: "hard",
      question: "Myanmar",
      options: ["Naypyidaw", "Yangon", "Mandalay", "Bago"],
    },
    {
      id: 36,
      difficulty: "hard",
      question: "Belarus",
      options: ["Minsk", "Gomel", "Mogilev", "Vitebsk"],
    },
    {
      id: 37,
      difficulty: "hard",
      question: "Azerbaijan",
      options: ["Baku", "Ganja", "Sumqayit", "Mingachevir"],
    },
    {
      id: 38,
      difficulty: "hard",
      question: "Georgia",
      options: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
    },
    {
      id: 39,
      difficulty: "hard",
      question: "Armenia",
      options: ["Yerevan", "Gyumri", "Vanadzor", "Hrazdan"],
    },
    {
      id: 40,
      difficulty: "hard",
      question: "Moldova",
      options: ["Chișinău", "Tiraspol", "Bălți", "Bender"],
    },
    {
      id: 41,
      difficulty: "hard",
      question: "Cyprus",
      options: ["Nicosia", "Limassol", "Larnaca", "Paphos"],
    },
    {
      id: 42,
      difficulty: "hard",
      question: "Luxembourg",
      options: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange"],
    },
    {
      id: 43,
      difficulty: "hard",
      question: "Liechtenstein",
      options: ["Vaduz", "Schaan", "Balzers", "Eschen"],
    },
    {
      id: 44,
      difficulty: "hard",
      question: "Malta",
      options: ["Valletta", "Sliema", "St. Julian's", "Birkirkara"],
    },
    {
      id: 45,
      difficulty: "hard",
      question: "Andorra",
      options: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana"],
    }
  ];